-- Опционально: если миграция из кода не сработала (редко). Обычно достаточно git pull + restart vpn-bot.
-- ALTER TABLE public.users ALTER COLUMN telegram_id TYPE BIGINT USING (telegram_id::bigint);
